[build]
publish = "slides/dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "24"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/what_is_quantum_computing/*"
to = "/slides/dist/what_is_quantum_computing/index.html"
status = 200

[[redirects]]
from = "/test/*"
to = "/slides/dist/test/index.html"
status = 200
